### PR TITLE
template CI workflow: do not run codecov coverage in CRON CI

### LINKED ISSUE #54: codecov upload limits cause failing CI
CI is failing from failure to upload to codecov, https://github.com/Becksteinlab/propkatraj/actions .

This should only cause failing CI when run for pull requests, but not for cron scheduled jobs.

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #54

Changes made in this Pull Request:
 - add condition on running codecov to exclude CRON CI

PR Checklist
------------
 - n/a Tests?
 - n/a Docs?
 - [x] CHANGELOG.md updated?
 - [x] AUTHORS.md updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Have to figure out how to protect `&&` for the templating
```
FAILED tests/test_output.py::test_write_outputs[n-DependencyType.CONDAFORGE] - jinja2.exceptions.TemplateSyntaxError: unexpected char '&' at 3799
```

**Comment by orbeckst** [comment]
Removing the unnecessary expression syntax `${{ ... }}` in `if:` avoided having to worry about to quote `${{ ... }}` for the jinja templating.

Still failing, although I don't understand (yet) why.

Also fails due to #56.

**Comment by orbeckst** [comment]
The error in actions "Error: Job 'main-tests' failed" and looking at the 10,000 lines of output does not reveal to me where the problem is.

@lilyminium @IAlibay @ianmkenney would you mind having a look?

**Comment by orbeckst** [comment]
Who knows, maybe it's just codecov ... and cycling the PR magically fixes things?

Btw, how are the differently numbered tests "GH Actions CI/main-tests-1", ..., "GH Actions CI/main-tests-12" generated and what do they do — are they different entries in the OS test matrix? I couldn't figure it out by looking at workflows and tests/ and in particular I don't understand what is really failing because each section says "success". There seem to be codecov upload errors (which still count as success) so that's why I am just pushing another silly commit.

**Comment by lilyminium** [comment]
Sorry for the delay, was pretty swamped with OMSF stuff. 

About the numbered tests -- yes sorry, I think you're referring to the cookie matrix of tests failing (since the cookie tests a matrix of settings). I usually comment them out if I have to debug something but it shows up very messily in the act output. I'll have a proper look when I get my laptop back tomorrow (eastern) morning.

**Review by lilyminium — APPROVED** [review]
LGTM -- thank you @orbeckst!

**Review by lilyminium — APPROVED** [review]
LGTM -- thank you @orbeckst!

**Pull request merged**
