### PR TITLE
Adding Python 3.11 to build matrix

### LINKED ISSUE #68: Cookie CI should test Python 3.11
As mentioned by @RMeli in #62, it might be worth testing Python 3.11 by default.

### PR DESCRIPTION
**Pull request by ianmkenney**
Fixes #68 

Changes made in this Pull Request:
 - Added Python 3.11 to the cookiecutter build matrix

### CODE REVIEW

**Comment by IAlibay** [comment]
I need to sleep a bit more, but I have an idea of how to build an action that would just change this to a dynamic matrix of Python versions supported by the current develop branch of MDAnalysis. Would that be a suitable idea here or would it add complexity to something that maybe doesn't need it?

**Comment by lilyminium** [comment]
IMO it depends how much complexity it would add -- these CI configs would ultimately be on the cookie maintainers to look after, so if it's very complicated than it may not be worth it. If you could abstract it away into an action that MDA maintains, that could work, but IMO you should leave room for packages that for some reason can't cover all the Python versions (eg their dependencies haven't updated yet) so their CI doesn't keep failing.

**Comment by IAlibay** [comment]
> IMO it depends how much complexity it would add -- these CI configs would ultimately be on the cookie maintainers to look after, so if it's very complicated than it may not be worth it. If you could abstract it away into an action that MDA maintains, that could work, but IMO you should leave room for packages that for some reason can't cover all the Python versions (eg their dependencies haven't updated yet) so their CI doesn't keep failing. 

Let me draft something up during my next couple days of isolation. If we think it's too much then I'm happy if we don't go ahead with it? In the meantime let's get this merged?

**Comment by lilyminium** [comment]
Happy to, yes — unfortunately I’m on a flight where GitHub just doesn’t load sometimes. LGTM from what I remember though, please go ahead. On May 19, 2023, at 15:33, Irfan Alibay ***@***.***> wrote:﻿

IMO it depends how much complexity it would add -- these CI configs would ultimately be on the cookie maintainers to look after, so if it's very complicated than it may not be worth it. If you could abstract it away into an action that MDA maintains, that could work, but IMO you should leave room for packages that for some reason can't cover all the Python versions (eg their dependencies haven't updated yet) so their CI doesn't keep failing.

Let me draft something up during my next couple days of isolation. If we think it's too much then I'm happy if we don't go ahead with it? In the meantime let's get this merged?

**Pull request merged**
