### PR TITLE
Make license badge consistent with license

### PR DESCRIPTION
**Pull request by RMeli**
Changes made in this Pull Request:
 - Make license badge consistent with license

The license badge says GPLv3, but the LICENSE file contains GPLv2.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG.md updated?
 - [ ] AUTHORS.md updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by RMeli** [comment]
The bottom of `README.md` is also inconsistent, mentioning GPLv3 but linking to the included GPLv2. Does the license need to be changed to GPLv3?

**Review by IAlibay — CHANGES_REQUESTED** [review]
We've got to be careful here, GPLv2 is not compatible with GPLv3 (it's the ultimate GNU trap card).

@lilyminium my understanding was that original aim was that this should have been GPLv2+, is this still not the case?

**Comment by lilyminium** [comment]
> @lilyminium my understanding was that original aim was that this should have been GPLv2+, is this still not the case?

My understanding was that for simplicity, this would be the same license as MDA is currently, which is GPLv2+.

**Review by lilyminium — APPROVED** [review]
Thanks so much for picking this up, @RMeli.

**Comment by IAlibay** [comment]
@lilyminium my point here is that GPLv2+ should be explicitly stated as "GPL version 2 or later" etc...

**Pull request merged**
